import { type ItemTypeClientDefinition } from '../shared';

export const CLOCK_TIME_ZONE_OPTIONS = [
  'America/Anchorage',
  'America/Argentina/Buenos_Aires',
  'America/Chicago',
  'America/Detroit',
  'America/Halifax',
  'America/Indiana/Indianapolis',
  'America/Kentucky/Louisville',
  'America/Los_Angeles',
  'America/St_Johns',
  'Asia/Bangkok',
  'Asia/Dhaka',
  'Asia/Dubai',
  'Asia/Hong_Kong',
  'Asia/Kabul',
  'Asia/Karachi',
  'Asia/Kathmandu',
  'Asia/Kolkata',
  'Asia/Seoul',
  'Asia/Singapore',
  'Asia/Tehran',
  'Asia/Tokyo',
  'Asia/Yangon',
  'Atlantic/Azores',
  'Atlantic/South_Georgia',
  'Australia/Brisbane',
  'Australia/Darwin',
  'Australia/Eucla',
  'Australia/Lord_Howe',
  'Europe/Berlin',
  'Europe/Helsinki',
  'Europe/London',
  'Europe/Moscow',
  'Pacific/Apia',
  'Pacific/Auckland',
  'Pacific/Chatham',
  'Pacific/Honolulu',
  'Pacific/Kiritimati',
  'Pacific/Noumea',
  'Pacific/Pago_Pago',
  'UTC',
] as const;

/** Default client-side UI definition for clock items. */
export const clockDefinition: ItemTypeClientDefinition = {
  type: 'clock',
  label: 'clock',
  editableProperties: ['title', 'timeZone', 'use24Hour'],
  globalProperties: {
    useSound: 'none',
    emitSound: 'sounds/clock.ogg',
    useCooldownMs: 1000,
    emitRange: 10,
    directional: false,
    emitSoundSpeed: 50,
    emitSoundTempo: 50,
  },
  propertyOptions: {
    timeZone: [...CLOCK_TIME_ZONE_OPTIONS],
  },
};
